### ISSUE TITLE
Cutting off 0's at beginning and end of MAC addresses

### ISSUE THREAD

**Issue by ajkblue** [R4phaB/4scan#1]
If a MAC address ends or begins with a 0 (zero), then it will be cut off an not show up in the scan.

For example, if there is a device on my network with a MAC address of "00:17:22:b5:ba:70", it would show up under 4scan as "0:17:22:b5:ba:7".

Other than that, everything seems to work great!

**Comment by R4phaB** [comment]
Hey ! Thank you for your feedback. Please take a look at the the commit #08ab046. Didn't have the issue so just test it, it should do the job.

**Comment by ajkblue** [comment]
That sort-of fixed it (some are shown correctly, while others still are not). Most of the addresses now correctly show their MAC if their are two zeros in front. It appears to be that if there is a zero in one of the last digits of the MAC, then the zero is incorrectly inserted at the beginning resulting in the first part of the MAC address having three digits/numbers. Another MAC address that has a problem was a zero that is supposed to be in the middle. Below is a screenshot of what 4scan shows and what the MAC addresses actually are:
![screen shot 2015-10-22 at 7 46 22 pm](https://cloud.githubusercontent.com/assets/9651939/10682847/50d7ed6e-78f8-11e5-8102-dbfaa601c0b8.png)

**Comment by R4phaB** [comment]
I misunderstood the problem. Unfortunately, I have currently no way to test it again. Hope the problem is now fixed in the last commit #be80ed2. Thank you very much for the interest !

**Comment by ajkblue** [comment]
That fixed it! All of the MAC address now display correctly. I've been looking for a good open-source WiFi scanner for some time now on OS X, and your app fits the bill perfectly. Thanks!
